server:
  port: 21902
spring:
  application:
    name: zipkin-item
  zipkin:
    base-url: http://localhost:21901
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
